# Generated by Django 6.0.5 on 2026-06-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogenerado',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
