# Generated by Django 6.0.5 on 2026-06-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productogenerado_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_fin_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_inicio_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(default='FREE', max_length=20),
        ),
    ]
