# Generated by Django 6.0.5 on 2026-06-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_fecha_fin_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogenerado',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productogenerado',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productogenerado',
            name='instruccion_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productogenerado',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productogenerado',
            name='material',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productogenerado',
            name='publico_objetivo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productogenerado',
            name='tono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
