# Generated by Django 6.0.5 on 2026-06-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productogenerado_categoria_productogenerado_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogenerado',
            name='imagen_publicitaria',
            field=models.ImageField(blank=True, null=True, upload_to='publicidad/'),
        ),
        migrations.AddField(
            model_name='productogenerado',
            name='prompt_imagen_publicitaria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
