# Generated by Django 6.0.5 on 2026-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
