# Generated by Django 6.0.5 on 2026-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='descripciones_hoy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_uso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='imagenes_hoy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
