# Generated by Django 6.0.5 on 2026-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_descripciones_hoy_customuser_fecha_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogenerado',
            name='imagen_publicitaria_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
