# Generated by Django 6.0.5 on 2026-07-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productogenerado_imagen_publicitaria_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
